# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 999
    schedule:
      interval: "daily"
    reviewers:
      - "laurelgh1234"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 999
    schedule:
      interval: "daily"
    commit-message:
      prefix: "TestPrefix"
      prefix-development: "TestDevPrefix"
      include: "scope"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 999
    schedule:
      interval: "daily"
